Update patch set 3
Patch Set 3:

> Great to hear, thanks!

Thanh,

I don't understand how build #7 did not have a protoc error, but build #8 did:

FileNotFoundError: [Errno 2] No such file or directory: 'protoc': 'protoc'

It appears that protoc is missing again. Was there another change made to the image after build #7?

Patch-set: 3