Update patch set 3
Patch Set 3:

> recheck

Unfortunately it appears that protoc is still missing from the image:

FileNotFoundError: [Errno 2] No such file or directory: 'protoc'

Patch-set: 3