Update patch set 10
Patch Set 10:

A new problem, can no longer install and test on Python 3.5 due to package zipp:

ERROR: Package 'zipp' requires a different Python: 3.5.7 not in '>=3.6'

Patch-set: 10