Update patch set 32
Patch Set 32:

The test seems to be failing because the new schema isn't there:

FileNotFoundError: [Errno 2] No such file or directory: '/w/workspace/acumos-python-client-pypi-verify-master/acumos/tests/schemas/schema-0.6.0.json'

I believe acumos/tests/schemas is a git submodule: https://github.com/acumos/acumos-python-client/tree/master/acumos/tests

So the submodule will need to pull the latest HEAD of the repo: https://www.vogella.com/tutorials/GitSubmodules/article.html#submodules_track

Patch-set: 32
Label: Code-Review=0