Update patch set 7
Patch Set 7: Code-Review-1

Philippe when I run tox locally it fails because of a problem finding the user-guide.rst file.  I don't think the change you added to find the docs directory is enough.  

Processing ./.tox/.tmp/package/1/acumos-0.9.1.zip
    ERROR: Command errored out with exit status 1:
     command: /Users/clott/git/acumos/acumos-python-client/acumos-package/.tox/py36/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2_/h72sys1530qcp756vs0l4phm0000gn/T/pip-req-build-oanz_sns/setup.py'"'"'; __file__='"'"'/private/var/folders/2_/h72sys1530qcp756vs0l4phm0000gn/T/pip-req-build-oanz_sns/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/2_/h72sys1530qcp756vs0l4phm0000gn/T/pip-req-build-oanz_sns/pip-egg-info
         cwd: /private/var/folders/2_/h72sys1530qcp756vs0l4phm0000gn/T/pip-req-build-oanz_sns/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2_/h72sys1530qcp756vs0l4phm0000gn/T/pip-req-build-oanz_sns/setup.py", line 62, in <module>
        long_description='\n'.join(_long_descr()),
      File "/private/var/folders/2_/h72sys1530qcp756vs0l4phm0000gn/T/pip-req-build-oanz_sns/setup.py", line 36, in _long_descr
        with open(doc_path) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/2_/h72sys1530qcp756vs0l4phm0000gn/T/docs/user-guide.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Patch-set: 7