Update patch set 2
Patch Set 2: Code-Review-1

Please run this simple test - it fails - need to adjust paths

(venv-py37) clott@mbp-cl778h:~/git/acumos/acumos-python-client/acumos-package% python setup.py 
Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    long_description='\n'.join(_long_descr()),
  File "setup.py", line 36, in _long_descr
    with open(doc_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/clott/git/acumos/acumos-python-client/acumos-package/docs/user-guide.rst'

Patch-set: 2
Label: Code-Review=-1