Update patch set 3
Patch Set 3:

> Patch Set 3: Code-Review-1
> 
> Did you test locally?  The job instantly fails for me:
> 
> (venv-py37) clott@mbp-cl778h:~/git/acumos/acumos-python-client/acumos-package% python setup.py 
> Traceback (most recent call last):
>   File "setup.py", line 24, in <module>
>     DOCS_DIR = path_join(split(SETUP_DIR)[0],'docs')
> NameError: name 'split' is not defined

Ok, I see I forgot to add split in from os.path

Patch-set: 3